'''
Created on 25 Dec 2013

@author: kevin
'''
import unittest
from io import StringIO
from configuration.configfile import ConfigFile


class Test(unittest.TestCase):


    def setUp(self):
        self.exampleConfigOne = '\n'.join([
            '# A config file for Whashose',
            '# phone: Must be a phone number, starting whith the country code',
            '# EG: Dutch (0031) mobile phone 06 12 34 56 78 would become 31612345678',
            'phone=31612345678',
            '# The password generated by yowsup CLI:',
            "password='mypassword'"])
        
        self.exampleConfigTwo = '\n'.join([
            '# This is an invalid file',
            'phonebla=123',
            "password='mypass'"])

    def tearDown(self):
        pass


    def testValidConfiguration(self):
        c = ConfigFile()
        c._readConfigFile(StringIO(self.exampleConfigOne))
        self.assertTrue(c.isValid(), "This configuration should be valid")
        
    def testInValidConfiguration(self):
        c = ConfigFile()
        c._readConfigFile(StringIO(self.exampleConfigTwo))
        self.assertFalse(c.isValid(), "This configuration should be invalid")
